# Generated by Django 5.1.6 on 2025-03-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JerseyDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jersey_type', models.CharField(max_length=20)),
                ('front_primary_color', models.CharField(max_length=7)),
                ('front_secondary_color', models.CharField(max_length=7)),
                ('front_text_color', models.CharField(max_length=7)),
                ('front_number', models.CharField(blank=True, max_length=2)),
                ('front_pattern', models.CharField(blank=True, max_length=50)),
                ('front_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('front_logo_size', models.FloatField(default=0.5)),
                ('back_primary_color', models.CharField(max_length=7)),
                ('back_secondary_color', models.CharField(max_length=7)),
                ('back_text_color', models.CharField(max_length=7)),
                ('back_name', models.CharField(blank=True, max_length=15)),
                ('back_number', models.CharField(blank=True, max_length=2)),
                ('back_pattern', models.CharField(blank=True, max_length=50)),
                ('back_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('back_logo_size', models.FloatField(default=0.5)),
            ],
        ),
    ]
